### ISSUE TITLE
Fix Main.py

### ISSUE THREAD

**Issue by etjones22** [iSTeeWx/python-minecraft-launcher#1]
Allow for other usernams apart from vlad...

import api
import os

def main() -> None:
    user_home = os.path.expanduser("~")
    game_path = os.path.join(user_home, "Documents/programming/python/launcher-recode/game-dir")
    api.start_game(game_path, "1.8.9")

if __name__ == '__main__':
    main()

**Comment by fcpoloia** [comment]
This still requires launcher folder to be `~/Documents/programming/python/launcher-recode/`, but doesn't account for a situation where program is located elsewhere in the operating system. A better approach would be to use `os.path.abspath(__file__)` to get the full path 

```python
import api
imprort os

def main() -> None:
    script_path = os.path.abspath(__file__)
    root = os.path.dirname(os.path.dirname(script_path))
    api.start_game("f{root}/game-dir", "1.8.9")


if __name__ == '__main__':
    main()
```

**Comment by etjones22** [comment]
Apologies, was just a quick look.
